<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>{{ name }}</title>
  <meta name="description" content="phaser tests">
  <meta name="author" content="dethbird">
  <script src="/js/pages/vendors~{{ name }}~production-dependencies.js"></script>
  <script src="/js/pages/production-dependencies.js"></script>
</head>

<body>
  <script src="/js/pages/{{ name }}.js"></script>
</body>
</html>
